apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: readercontainer
  name: readercontainer
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: readercontainer
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: readercontainer
    spec:
      containers:
        - image: rahulawari683/reader-dockerhub-repo:latest 
          name: readercontainer
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /shared
              name: shared-data
      restartPolicy: Always
      volumes:
        - name: shared-data
          persistentVolumeClaim:
            claimName: shared-data
