apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: "kompose convert"
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: readercontainer
  name: readercontainer
  namespace: argocdtestingcontainer
spec:
  ports: # cluster ip type 
    - name: "8080"
      port: 8080  #service port
      targetPort: 80 #backend port
  selector:
    io.kompose.service: readercontainer