apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: "kompose convert"
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: reversecontainer
  name: reversecontainer
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: reversecontainer
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: "kompose convert"
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: reversecontainer
    spec:
      containers:
        - image: rahulawari683/reverse-dockerhub-repo:latest
          name: reversecontainer
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /shared
              name: shared-data
          resources:
            requests:
              cpu: 1m
              memory: 50Mi
            limits:
              cpu: 75m
              memory: 128Mi
      restartPolicy: Always
      volumes:
        - name: shared-data
          persistentVolumeClaim:
            claimName: shared-data