apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: shared-data
  name: shared-data
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
